name: "Build the OpenSalamander project"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Project files expect this variable to be defined.
  OPENSAL_BUILD_DIR: c:\\OpenSalamander\\
  # Directory with installation that will be packed and uploaded as an artifact.
  OPENSAL_INSTALL_DIR: c:\\install\\OpenSalamander\\
  # Configuration type to build.
  BUILD_CONFIGURATION: Release

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        targetplatform: [x86]  # x64, arm64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create version file
      run: |
        mkdir ${{ env.OPENSAL_INSTALL_DIR }}
        git describe --tags --always > ${{ env.OPENSAL_INSTALL_DIR }}version.txt
        type ${{ env.OPENSAL_INSTALL_DIR }}version.txt
  
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup .NET Framework SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' # required for pe-viewer

    - name: Setup vcpkg
      run: |
        bootstrap-vcpkg
        vcpkg integrate install

    - name: Build the project
      run: msbuild src\vcxproj\salamand.sln /t:Rebuild /p:Configuration=Release

    - name: Compose installation directory
      run: |
        pushd${{ env.OPENSAL_BUILD_DIR }}salamander\\${{ env.BUILD_CONFIGURATION }}_${{ matrix.targetplatform }}
        robocopy . ${{ env.OPENSAL_INSTALL_DIR }} *.exe *.dll *.spl *.slg /S
        popd
        xcopy /E /I /Y ${{ github.workspace }}\\convert ${{ env.OPENSAL_INSTALL_DIR }}convert
        xcopy /E /I /Y ${{ github.workspace }}\\doc ${{ env.OPENSAL_INSTALL_DIR }}doc
        xcopy /E /I /Y ${{ github.workspace }}\\src\\res\\toolbars ${{ env.OPENSAL_INSTALL_DIR }}toolbars
        xcopy /E /I /Y ${{ github.workspace }}\\src\\plugins\\automation\\sample-scripts ${{ env.OPENSAL_INSTALL_DIR }}plugins\\automation\\scripts
        xcopy /E /I /Y ${{ github.workspace }}\\src\\plugins\\ieviewer\\cmark-gfm\\css ${{ env.OPENSAL_INSTALL_DIR }}plugins\\ieviewer\\css
        xcopy /I /Y ${{ github.workspace }}\\src\\plugins\\zip\\zip2sfx\\*.txt ${{ env.OPENSAL_INSTALL_DIR }}plugins\\zip\\zip2sfx
        xcopy /I /Y ${{ github.workspace }}\\src\\plugins\\zip\\zip2sfx\\*.set ${{ env.OPENSAL_INSTALL_DIR }}plugins\\zip\\zip2sfx

    - name: Finalize installation package
      uses: actions/upload-artifact@v4
      with:
        name: OpenSalamander-${{ matrix.targetplatform }}
        path: ${{ env.OPENSAL_INSTALL_DIR }}
        retention-days: 10
